### ISSUE TITLE
Mapa Mental Ingenieria de Requerimentos

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Aricel117#1]
[Ingenieria de requerimentos Mapa Mental (18620252).pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-Aricel117/files/10712650/Ingenieria.de.requerimentos.Mapa.Mental.18620252.pdf)

**Comment by Gregorio012** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
